### ISSUE TITLE
Find the one true code

### ISSUE THREAD

**Issue by david-loffredo** [plutoscarab/Rails#1]
Opening issue to have a place for any discussion.    From the conversation that kicked this off:

> Added a repository called Rails with empty main branch and five option branches. Good code is probably one of the first three.

Will dig into the branches over the next week or two.   BTW, the old exec that I am running has an about box with a single line "PC Rails version 1.0.2078.34801"

**Comment by david-loffredo** [comment]
Option1 seems the newest, should be merged to main.   Option3 is also a good older checkpoint, perhaps keep around in a pre-network play branch.

## Discussion

I analyzed the source and then built all of the branches and tested them out.  I needed to comment out the strong name key, un-comment the bmp generator functions in the Graphics subdir, and also changed the registry keys from LocalMachine to CurrentUser so that it no longer needs admin privs.  I started with VS 2012, since it was the oldest devenv that I had available, and none of the setup projects were supported anymore.

Option1 seems the newest, with a launcher dialog, new/old style maps, and some form of LAN play.  The source for O1 is the most extensive, with the most extensive set of icons and train images.   
![o1_main](https://user-images.githubusercontent.com/8879578/198188703-1a5426f0-134b-40d0-bdfb-72359e04f34c.png)
![o1_newgame](https://user-images.githubusercontent.com/8879578/198188720-20255b3c-ee0b-4d3b-af14-d381998f7bab.png)

Option2 is not functional and seems to be an intermediate stage between O3 and O1.  It has a launcher dialog with a train image, and options for local or network play.  None of the buttons do anything.
![o2_main](https://user-images.githubusercontent.com/8879578/198188790-ab9a74c0-88bc-4b15-ae5b-553d76adc128.png)

It seems like option3 is the oldest version, It boots directly into
the new game dialog and has a checkbox for new/old style maps.  It is
newer than what I have been playing, which is similar but without the
new/old map option.
![o3_newgame](https://user-images.githubusercontent.com/8879578/198188812-e8f6b0c0-0588-49f4-9698-7e12a157a624.png)

Option4 and Option5 are variations of O1, without a map editor, one
with and one without setup projects.

**Comment by plutoscarab** [comment]
ok, I merged option 1 branch into main. Thanks for taking the time to figure this out.
